=== api-evangelist/reqres/json-schema/reqres-legacy-unknown-list-response-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/reqres/refs/heads/main/json-schema/reqres-legacy-unknown-list-response-schema.json",
  "title": "LegacyUnknownListResponse",
  "description": "LegacyUnknownListResponse schema from ReqRes API",
  "type": "object",
  "properties": {
    "page": {
      "type": "integer"
    },
    "per_page": {
      "type": "integer"
    },
    "total": {
      "type": "integer"
    },
    "total_pages": {
      "type": "integer"
    },
    "data": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "name": {
            "type": "string"
          },
          "year": {
            "type": "integer"
          },
          "color": {
            "type": "string"
          },
          "pantone_value": {
            "type": "string"
          }
        },
        "required": [
          "id",
          "name",
          "year",
          "color",
          "pantone_value"
        ]
      }
    },
    "support": {
      "type": "object",
      "additionalProperties": true
    }
  },
  "required": [
    "page",
    "per_page",
    "total",
    "total_pages",
    "data"
  ],
  "additionalProperties": true
}

=== api-evangelist/reqres/examples/reqres-legacy-unknown-list-response-example.json
{
  "page": 1,
  "per_page": 1,
  "total": 12,
  "total_pages": 1,
  "data": [
    {
      "id": 7,
      "name": "morpheus",
      "year": 13,
      "color": "#5cae31",
      "pantone_value": "17-1456"
    },
    {
      "id": 7,
      "name": "morpheus",
      "year": 88,
      "color": "#5cae31",
      "pantone_value": "17-1456"
    }
  ],
  "support": {}
}
